repo_loc: "/Users/davidgreis/Documents/Personal/Data_Projects/ML"
current_project: "bank_marketing"

model_facet_defaults:
    keyword_arg_settings : {}
    other_options: {}
    feature_settings:
        feature_engineering: []
        select_before_eng: False
        feature_selection: []
    cross_validation_settings: None



metrics:
  binary-classification:
      battery:
        precision_recall_curve:
          metric_type: unknown
          kwargs: {}
        roc_curve:
          metric_type: unknown
          kwargs: {}
  multiclass-classification:
        battery:
          confusion_matrix:
            metric_type: array
            kwargs: {}
          accuracy_score:
            metric_type: column
            kwargs: {}
          classification_report:
            metric_type: classification_report
            kwargs: {}
          f1_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          recall_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          precision_score:
            metric_type: column
            kwargs: { "average" : "weighted" }


