repo_loc: "/Users/davidgreis/Documents/Personal/Data_Projects/ML"
current_project: "human_activity"

model_facet_defaults:
    keyword_arg_settings : {}
    feature_settings:
        exclusion_patterns: None
    cross_validation_settings: None

module_map:
  multiclass-classification: 'classification'
  binary-classification: 'classfication'
  regression: 'regression'

metrics:
  binary-classification:
      - precision_recall_curve
      - roc_curve
  multiclass-classification:
        standard_keyword_args:
          average: 'weighted'
        battery:
          confusion_matrix:
            metric_type: array
            kwargs: {}
          accuracy_score:
            metric_type: column
            kwargs: {}
          classification_report:
            metric_type: text
            kwargs: {}
          f1_score:
            metric_type: column
          recall_score:
            metric_type: column
          precision_score:
            metric_type: column


