repo_loc: "/Users/davidgreis/Documents/Personal/Data_Projects/ML"
current_project: "car_evaluation"

model_facet_defaults:
    keyword_arg_settings : {}
    other_options: {}
    feature_settings:
        feature_engineering: []
        select_before_eng: False
        feature_selection: []
    cross_validation_settings: None



metrics:
  binary-classification:
      - precision_recall_curve
      - roc_curve
  multiclass-classification:
        standard_keyword_args:
          average: 'weighted'
        battery:
          confusion_matrix:
            metric_type: array
            kwargs: {}
          accuracy_score:
            metric_type: column
            kwargs: {}
          classification_report:
            metric_type: classification_report
            kwargs: {}
          f1_score:
            metric_type: column
          recall_score:
            metric_type: column
          precision_score:
            metric_type: column


