repo_loc: "/Users/davidgreis/Documents/Personal/Data_Projects/ML"
current_project: "human_activity"

model_facet_defaults:
    keyword_arg_settings : {}
    other_options: {}
    feature_settings:
        feature_engineering: []
        select_before_eng: False
        feature_selection: []
    hyperparam_tuning_settings: None
    evaluate_testset: False

assessment:
  cv_num_folds: 5

metrics:
  regression:
      battery:
        explained_variance_score:
          metric_type: column
          kwargs: {}
        mean_squared_error:
          metric_type: column
          kwargs: {}
        median_absolute_error:
          metric_type: column
          kwargs: {}
        r2_score:
          metric_type: column
          kwargs: {}
  binary-classification:
      battery:
        precision_recall_curve:
          metric_type: unknown
          kwargs: {}
        roc_curve:
          metric_type: unknown
          kwargs: {}
  multiclass-classification:
        battery:
          confusion_matrix:
            metric_type: array
            kwargs: {}
          accuracy_score:
            metric_type: column
            kwargs: {}
          classification_report:
            metric_type: classification_report
            kwargs: {}
          roc_auc_score:
            metric_type: column
            kwargs: { "average" : 'None' }
          f1_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          recall_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          precision_score:
            metric_type: column
            kwargs: { "average" : "weighted" }


