repo_loc: "/Users/davidgreis/Documents/Personal/Data_Projects/ML"
current_project: "forest_cover"
remote_settings:
  remote_deploy: True
  remote_repo_loc: '/ML/'
  s3_bucket: 'remote-ml-greis-test'
  docker_image: 'dgreis/ml:latest'
  environment_mode: 'EC2'
  aws:
    #instance_type: 'p2.xlarge'
    #instance_type: 'p3.2xlarge'
    instance_type: t2.large
model_facet_defaults:
    base_algorithm: None
    keyword_arg_settings : {}
    feature_settings:
        manipulations: []
    hyperparam_tuning_settings: None
    evaluate_testset: False
    dump_design: False
    output: []
    cv_num_folds: 5
    train_val_split: 0.8

metrics:
  regression:
      battery:
        explained_variance_score:
          metric_type: column
          kwargs: {}
        mean_squared_error:
          metric_type: column
          kwargs: {}
        median_absolute_error:
          metric_type: column
          kwargs: {}
        r2_score:
          metric_type: column
          kwargs: {}
        rmsle:
          metric_type: column
          kwargs: {}
  binary-classification:
      battery:
        precision_recall_curve:
          metric_type: unknown
          kwargs: {}
        roc_curve:
          metric_type: unknown
          kwargs: {}
  multiclass-classification:
        battery:
          confusion_matrix:
            metric_type: array
            kwargs: {}
          accuracy_score:
            metric_type: column
            kwargs: {}
          classification_report:
            metric_type: classification_report
            kwargs: {}
#          roc_auc_score:         #Not supported in multi-class without more work
#            metric_type: column
#            kwargs: { "average" : 'macro' }
          f1_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          recall_score:
            metric_type: column
            kwargs: { "average" : "weighted" }
          precision_score:
            metric_type: column
            kwargs: { "average" : "weighted" }


overwritten_algos:  []