project_name : "bank_marketing"
ml_problem_type: 'binary-classification'
data_dir : "data/bank"
#parse_sep : "'\s+"
parse_engine: "python"
train_test_split: 0.75
raw_input_files:
  X : "bank-full.csv"
clean_input_files:
  X_train : "processed/X_train.txt"
  y_train : "processed/y_train.txt"
  X_train_val: "processed/X_train_val.txt"
  y_train_val: "processed/y_train_val.txt"
  X_val: "processed/X_val.txt"
  y_val: "processed/y_val.txt"
  X_test: "processed/X_test.txt"
  y_test : "processed/y_test.txt"
  feature_names: "processed/features.txt"

metrics:
  multiclass-classification:
        battery:
          f1_score:
            metric_type: column
            kwargs: { "average" : "macro" }
          recall_score:
            metric_type: column
            kwargs: { "average" : "macro" }
          precision_score:
            metric_type: column
            kwargs: { "average" : "macro" }