project_name : "bank_marketing"
ml_problem_type: 'binary-classification'
data_dir : "data/bank"
#parse_sep : "'\s+"
parse_engine: "python"
test_train_split: 0.7
raw_input_files:
  X : "bank-full.csv"
clean_input_files:
  X_train : "processed/X_train.txt"
  y_train : "processed/y_train.txt"
  X_test : "processed/X_test.txt"
  y_test : "processed/y_test.txt"
  feature_names: "processed/features.txt"