
project_name : "human_activity"
ml_problem_type: 'classification'
data_dir : "data/UCI HAR Dataset"
files:
  x_train : "train/X_train.txt"
  y_train : "train/y_train.txt"
  x_test : "test/x_test.txt"
  y_test : "test/y_test.txt"