
project_name : "car_evaluation"
ml_problem_type: 'multiclass-classification'
data_dir : "data"
#parse_sep : "'\s+"
parse_engine: "python"
test_train_split: 0.7
preprocessed_input_files:
  X : "car.data.txt"
clean_input_files:
  X_train : "processed/X_train.txt"
  y_train : "processed/y_train.txt"
  X_test : "processed/x_test.txt"
  y_test : "processed/y_test.txt"
  feature_names: "processed/features.txt"