
project_name : "human_activity"
ml_problem_type: 'multiclass-classification'
data_dir : "data/UCI HAR Dataset"
#parse_sep : "'\s+"
parse_engine: "python"
raw_input_files:
  feature_names: "features.txt"
clean_input_files:
  X_train_val : "train/X_train.txt"
  y_train_val : "train/y_train.txt"
  X_test : "test/x_test.txt"
  y_test : "test/y_test.txt"
  X_train: "processed/X_train.txt"
  y_train: "processed/y_train.txt"
  X_val: "processed/X_val.txt"
  y_val: "processed/y_val.txt"
  feature_names: "processed/features.txt"